version: '3.8'
services:
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"